In [41]:
import pandas as pd
import mygene
from datasets import Commpass

In [15]:
expr_df = pd.read_csv("../../data/CoMMpass/1stLine_Raw_ENSG.csv").set_index("Unnamed: 0").transpose()

In [49]:
expr_df

Unnamed: 0,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000293563,ENSG00000293564,ENSG00000293565,ENSG00000293569,ENSG00000293570,ENSG00000293575,ENSG00000293584,ENSG00000293594,ENSG00000293600,ENSG00000293604
MMRF_1021,983.431,0.0,1429.197,878.069,358.350,25.000,3936.536,1706.000,1241.614,1433.000,...,78.619,0.0,0.0,21.342,120.937,0.0,0.0,0.0,345.798,279.331
MMRF_1024,778.364,0.0,992.826,792.502,112.334,485.000,42.895,2041.294,1068.236,1226.602,...,14.590,0.0,0.0,8.424,33.000,0.0,0.0,0.0,497.271,244.025
MMRF_1029,1511.232,0.0,2361.995,1427.285,322.082,36.000,119.918,6258.703,2151.640,4731.511,...,75.272,0.0,0.0,37.901,140.002,0.0,0.0,0.0,247.963,964.733
MMRF_1030,89.162,0.0,1289.525,590.339,104.087,41.000,76.128,2721.211,842.639,1044.942,...,1.891,0.0,0.0,18.584,132.000,0.0,0.0,0.0,604.834,534.993
MMRF_1031,14.301,0.0,1158.047,623.536,448.943,46.000,172.394,3697.625,1076.339,2144.931,...,39.219,0.0,0.0,14.688,24.000,0.0,0.0,0.0,791.640,846.260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MMRF_2843,31.073,0.0,4754.252,661.462,135.058,304.000,177.539,1540.344,2553.042,869.910,...,0.000,0.0,0.0,99.736,315.000,0.0,0.0,0.0,40.251,2103.901
MMRF_2847,180.655,0.0,3874.189,597.216,312.844,1739.000,1202.797,531.938,740.401,959.005,...,71.217,0.0,0.0,75.938,56.000,0.0,0.0,0.0,194.059,1184.209
MMRF_2848,184.549,0.0,2594.010,685.064,121.585,5219.602,876.724,3729.078,687.257,2215.362,...,8.385,0.0,0.0,85.619,72.000,0.0,0.0,0.0,169.604,454.409
MMRF_2851,38.587,0.0,4096.867,713.223,164.807,496.000,286.678,1308.000,1148.025,983.000,...,0.000,0.0,0.0,70.915,145.001,0.0,0.0,0.0,276.826,958.819
MMRF_2853,40.211,0.0,2532.244,1962.360,222.085,168.000,524.496,241.001,1626.349,850.834,...,0.000,0.0,0.0,151.620,396.000,0.0,0.0,0.0,64.273,336.355

In [21]:
import mygene
mg = mygene.MyGeneInfo()
out = mg.querymany(list(expr_df.columns), scopes="ensembl.gene", fields="type_of_gene,symbol", species="human")

31 input query terms found dup hits:	[('ENSG00000117262', 2), ('ENSG00000188092', 2), ('ENSG00000215156', 2), ('ENSG00000267635', 2), ('E
22 input query terms found no hit:	['ENSG00000002079', 'ENSG00000139656', 'ENSG00000148362', 'ENSG00000169789', 'ENSG00000169807', 'ENS

In [38]:
mg_df = pd.DataFrame(out) 
mg_df

,query,_id,_score,symbol,type_of_gene,notfound
0,ENSG00000000003,7105,32.287030,TSPAN6,protein-coding,NaN
1,ENSG00000000005,64102,32.287563,TNMD,protein-coding,NaN
2,ENSG00000000419,8813,31.314926,DPM1,protein-coding,NaN
3,ENSG00000000457,57147,32.287075,SCYL3,protein-coding,NaN
4,ENSG00000000460,55732,32.290184,FIRRM,protein-coding,NaN
...,...,...,...,...,...,...
38474,ENSG00000293575,ENSG00000293575,32.287030,NaN,NaN,NaN
38475,ENSG00000293584,ENSG00000293584,32.287548,NaN,NaN,NaN
38476,ENSG00000293594,ENSG00000293594,32.287563,NaN,NaN,NaN
38477,ENSG00000293600,131768270,32.287030,LOC131768270,protein-coding,NaN
38478,ENSG00000293604,84876,31.314432,ORAI1,protein-coding,NaN

In [39]:
mg_df = mg_df[(mg_df['type_of_gene'] == 'protein-coding') & (mg_df["symbol"].notna())].drop_duplicates(subset="symbol", keep="first")

In [40]:
mg_df

,query,_id,_score,symbol,type_of_gene,notfound
0,ENSG00000000003,7105,32.287030,TSPAN6,protein-coding,NaN
1,ENSG00000000005,64102,32.287563,TNMD,protein-coding,NaN
2,ENSG00000000419,8813,31.314926,DPM1,protein-coding,NaN
3,ENSG00000000457,57147,32.287075,SCYL3,protein-coding,NaN
4,ENSG00000000460,55732,32.290184,FIRRM,protein-coding,NaN
...,...,...,...,...,...,...
38462,ENSG00000293543,128854680,32.287563,DUSP13A,protein-coding,NaN
38465,ENSG00000293551,653606,31.315428,PRAMEF22,protein-coding,NaN
38470,ENSG00000293564,139427322,32.287075,LOC139427322,protein-coding,NaN
38477,ENSG00000293600,131768270,32.287030,LOC131768270,protein-coding,NaN
38478,ENSG00000293604,84876,31.314432,ORAI1,protein-coding,NaN

In [50]:
ad = Commpass.load_commpass_ad()

/usr/lib/python3.14/functools.py:982: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

CoMMpass Annotated data found!

In [ ]:
ad.to_df() # should these even be integers??

,TSPAN6,TNMD,DPM1,CCL15,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,...,SMIM46,GUCA1ANB-GUCA1A,HOMEZ,H2BN1,SOD2,POLGARF,LY6S,TMEM276-ZFTRAF1,TMEM276,DUSP13A
PUBLIC_ID,,,,,,,,,,,,,,,,,,,,,
MMRF_1078,13.0,0.0,1036.0,366.0,366.0,159.0,32.0,76.0,1715.0,567.0,...,0.0,0.0,229.0,6.0,3440.0,0.0,262.0,211.0,682.0,0.0
MMRF_1670,261.0,1.0,2601.0,929.0,929.0,644.0,531.0,8511.0,4426.0,2244.0,...,0.0,0.0,833.0,13.0,7019.0,0.0,392.0,0.0,1178.0,0.0
MMRF_2691,212.0,0.0,1559.0,963.0,963.0,410.0,859.0,1072.0,1583.0,753.0,...,0.0,0.0,642.0,8.0,7888.0,0.0,649.0,1.0,2217.0,1.0
MMRF_2557,112.0,0.0,1964.0,997.0,997.0,330.0,37.0,437.0,3325.0,1180.0,...,0.0,0.0,818.0,8.0,11308.0,0.0,1155.0,0.0,1374.0,0.0
MMRF_1458,164.0,0.0,2303.0,1028.0,1028.0,284.0,229.0,527.0,1647.0,1028.0,...,0.0,0.0,1130.0,15.0,13897.0,0.0,1487.0,98.0,3648.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MMRF_2739,108.0,0.0,7351.0,3483.0,3483.0,3898.0,388.0,276.0,8855.0,3961.0,...,0.0,0.0,1561.0,5.0,13874.0,0.0,660.0,73.0,1447.0,0.0
MMRF_2293,107.0,1.0,1695.0,1568.0,1568.0,290.0,107.0,253.0,1453.0,1603.0,...,0.0,0.0,933.0,8.0,7387.0,0.0,605.0,0.0,1331.0,0.0
MMRF_2413,52.0,1.0,1954.0,743.0,743.0,285.0,34.0,427.0,6834.0,1215.0,...,0.0,0.0,854.0,12.0,9248.0,0.0,688.0,87.0,1381.0,0.0
MMRF_2455,29.0,0.0,1642.0,1232.0,1232.0,741.0,470.0,327.0,1799.0,608.0,...,0.0,0.0,731.0,8.0,5683.0,0.0,297.0,110.0,1818.0,0.0
MMRF_1308,241.0,0.0,3163.0,1177.0,1177.0,798.0,216.0,393.0,4584.0,2370.0,...,0.0,0.0,659.0,3.0,9327.0,0.0,687.0,87.0,1426.0,0.0