In [ ]:
from datasets import Moffitt

In [16]:
ad = Moffitt.load_moffitt_ad()

/usr/lib/python3.14/functools.py:982: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

Creating Annotated data file for moffitt ...

742 input query terms found dup hits:	[('ACAT1', 2), ('ACAT2', 2), ('ACP1', 2), ('ADA2', 2), ('ADAM18', 2), ('ADCY3', 2), ('ADK', 2), ('AD
583 input query terms found no hit:	['AC000093.1', 'AC000120.2', 'AC000120.3', 'AC001226.2', 'AC002094.3', 'AC002310.4', 'AC002985.1', '

[{'query': 'A1BG', '_id': '1', '_score': 19.544168, 'entrezgene': '1', 'type_of_gene': 'protein-coding'}, {'query': 'A1CF', '_id': '29974', '_score': 17.505005, 'entrezgene': '29974', 'type_of_gene': 'protein-coding'}, {'query': 'A2M', '_id': '2', '_score': 19.293959, 'entrezgene': '2', 'type_of_gene': 'protein-coding'}, {'query': 'A2ML1', '_id': '144568', '_score': 19.149, 'entrezgene': '144568', 'type_of_gene': 'protein-coding'}, {'query': 'A3GALT2', '_id': '127550', '_score': 19.181055, 'entrezgene': '127550', 'type_of_gene': 'protein-coding'}, {'query': 'A4GALT', '_id': '53947', '_score': 18.544558, 'entrezgene': '53947', 'type_of_gene': 'protein-coding'}, {'query': 'A4GNT', '_id': '51146', '_score': 18.383066, 'entrezgene': '51146', 'type_of_gene': 'protein-coding'}, {'query': 'AAAS', '_id': '8086', '_score': 17.484211, 'entrezgene': '8086', 'type_of_gene': 'protein-coding'}, {'query': 'AACS', '_id': '65985', '_score': 17.43726, 'entrezgene': '65985', 'type_of_gene': 'protein-coding'}, {'query': 'AADAC', '_id': '13', '_score': 17.91258, 'entrezgene': '13', 'type_of_gene': 'protein-coding'}, {'query': 'AADACL2', '_id': '344752', '_score': 20.450562, 'entrezgene': '344752', 'type_of_gene': 'protein-coding'}, {'query': 'AADACL3', '_id': '126767', '_score': 19.891819, 'entrezgene': '126767', 'type_of_gene': 'protein-coding'}, {'query': 'AADACL4', '_id': '343066', '_score': 18.679756, 'entrezgene': '343066', 'type_of_gene': 'protein-coding'}, {'query': 'AADAT', '_id': '51166', '_score': 17.564842, 'entrezgene': '51166', 'type_of_gene': 'protein-coding'}, {'query': 'AAGAB', '_id': '79719', '_score': 17.466831, 'entrezgene': '79719', 'type_of_gene': 'protein-coding'}, {'query': 'AAK1', '_id': '22848', '_score': 18.117064, 'entrezgene': '22848', 'type_of_gene': 'protein-coding'}, {'query': 'AAMDC', '_id': '28971', '_score': 17.491728, 'entrezgene': '28971', 'type_of_gene': 'protein-coding'}, {'query': 'AAMP', '_id': '14', '_score': 17.453, 'entrezgene': '14', 'type_of_gene': 'protein-coding'}, {'query': 'AANAT', '_id': '15', '_score': 18.075607, 'entrezgene': '15', 'type_of_gene': 'protein-coding'}, {'query': 'AAR2', '_id': '25980', '_score': 17.390154, 'entrezgene': '25980', 'type_of_gene': 'protein-coding'}, {'query': 'AARD', '_id': '441376', '_score': 18.181236, 'entrezgene': '441376', 'type_of_gene': 'protein-coding'}, {'query': 'AARS', '_id': '16', '_score': 16.987206, 'entrezgene': '16', 'type_of_gene': 'protein-coding'}, {'query': 'AARS2', '_id': '57505', '_score': 17.495375, 'entrezgene': '57505', 'type_of_gene': 'protein-coding'}, {'query': 'AARSD1', '_id': '80755', '_score': 18.113438, 'entrezgene': '80755', 'type_of_gene': 'protein-coding'}, {'query': 'AASDH', '_id': '132949', '_score': 16.889643, 'entrezgene': '132949', 'type_of_gene': 'protein-coding'}, {'query': 'AASDHPPT', '_id': '60496', '_score': 17.4367, 'entrezgene': '60496', 'type_of_gene': 'protein-coding'}, {'query': 'AASS', '_id': '10157', '_score': 17.434097, 'entrezgene': '10157', 'type_of_gene': 'protein-coding'}, {'query': 'AATF', '_id': '26574', '_score': 16.959118, 'entrezgene': '26574', 'type_of_gene': 'protein-coding'}, {'query': 'AATK', '_id': '9625', '_score': 16.2024, 'entrezgene': '9625', 'type_of_gene': 'protein-coding'}, {'query': 'ABAT', '_id': '18', '_score': 17.454313, 'entrezgene': '18', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA1', '_id': '19', '_score': 18.071129, 'entrezgene': '19', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA10', '_id': '10349', '_score': 20.800491, 'entrezgene': '10349', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA12', '_id': '26154', '_score': 17.518925, 'entrezgene': '26154', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA13', '_id': '154664', '_score': 18.560846, 'entrezgene': '154664', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA2', '_id': '20', '_score': 17.51545, 'entrezgene': '20', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA3', '_id': '21', '_score': 17.833866, 'entrezgene': '21', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA4', '_id': '24', '_score': 18.143581, 'entrezgene': '24', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA5', '_id': '23461', '_score': 17.499725, 'entrezgene': '23461', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA6', '_id': '23460', '_score': 19.669613, 'entrezgene': '23460', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA7', '_id': '10347', '_score': 17.685034, 'entrezgene': '10347', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA8', '_id': '10351', '_score': 20.792898, 'entrezgene': '10351', 'type_of_gene': 'protein-coding'}, {'query': 'ABCA9', '_id': '10350', '_score': 19.796959, 'entrezgene': '10350', 'type_of_gene': 'protein-coding'}, {'query': 'ABCB1', '_id': '5243', '_score': 18.594769, 'entrezgene': '5243', 'type_of_gene': 'protein-coding'}, {'query': 'ABCB10', '_id': '23456', '_score': 17.429571, 'entrezgene': '23456', 'type_of_gene': 'protein-coding'}, {'query': 'ABCB11', '_id': '8647', '_score': 18.142298, 'entrezgene': '8647', 'type_of_gene': 'protein-coding'}, {'query': 'ABCB4', '_id': '5244', '_score': 18.183544, 'entrezgene': '5244', 'type_of_gene': 'protein-coding'}, {'query': 'ABCB5', '_id': '340273', '_score': 18.10614, 'entrezgene': '340273', 'type_of_gene': 'protein-coding'}, {'query': 'ABCB6', '_id': '10058', '_score': 18.071436, 'entrezgene': '10058', 'type_of_gene': 'protein-coding'}, {'query': 'ABCB7', '_id': '22', '_score': 16.875402, 'entrezgene': '22', 'type_of_gene': 'protein-coding'}, {'query': 'ABCB8', '_id': '11194', '_score': 17.557415, 'entrezgene': '11194', 'type_of_gene': 'protein-coding'}, {'query': 'ABCB9', '_id': '23457', '_score': 17.485802, 'entrezgene': '23457', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC1', '_id': '4363', '_score': 17.797638, 'entrezgene': '4363', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC10', '_id': '89845', '_score': 17.475021, 'entrezgene': '89845', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC11', '_id': '85320', '_score': 19.721395, 'entrezgene': '85320', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC12', '_id': '94160', '_score': 18.242882, 'entrezgene': '94160', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC2', '_id': '1244', '_score': 17.51707, 'entrezgene': '1244', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC3', '_id': '8714', '_score': 17.449543, 'entrezgene': '8714', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC4', '_id': '10257', '_score': 17.572252, 'entrezgene': '10257', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC5', '_id': '10057', '_score': 17.606226, 'entrezgene': '10057', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC6', '_id': '368', '_score': 18.400879, 'entrezgene': '368', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC8', '_id': '6833', '_score': 17.466715, 'entrezgene': '6833', 'type_of_gene': 'protein-coding'}, {'query': 'ABCC9', '_id': '10060', '_score': 17.524277, 'entrezgene': '10060', 'type_of_gene': 'protein-coding'}, {'query': 'ABCD1', '_id': '215', '_score': 17.779844, 'entrezgene': '215', 'type_of_gene': 'protein-coding'}, {'query': 'ABCD2', '_id': '225', '_score': 17.674393, 'entrezgene': '225', 'type_of_gene': 'protein-coding'}, {'query': 'ABCD3', '_id': '5825', '_score': 17.891392, 'entrezgene': '5825', 'type_of_gene': 'protein-coding'}, {'query': 'ABCD4', '_id': '5826', '_score': 17.434181, 'entrezgene': '5826', 'type_of_gene': 'protein-coding'}, {'query': 'ABCE1', '_id': '6059', '_score': 17.446136, 'entrezgene': '6059', 'type_of_gene': 'protein-coding'}, {'query': 'ABCF1', '_id': '23', '_score': 17.624575, 'entrezgene': '23', 'type_of_gene': 'protein-coding'}, {'query': 'ABCF2', '_id': '10061', '_score': 18.487938, 'entrezgene': '10061', 'type_of_gene': 'protein-coding'}, {'query': 'ABCF3', '_id': '55324', '_score': 17.402205, 'entrezgene': '55324', 'type_of_gene': 'protein-coding'}, {'query': 'ABCG1', '_id': '9619', '_score': 17.53689, 'entrezgene': '9619', 'type_of_gene': 'protein-coding'}, {'query': 'ABCG2', '_id': '9429', '_score': 18.477446, 'entrezgene': '9429', 'type_of_gene': 'protein-coding'}, {'query': 'ABCG4', '_id': '64137', '_score': 18.11066, 'entrezgene': '64137', 'type_of_gene': 'protein-coding'}, {'query': 'ABCG5', '_id': '64240', '_score': 17.423449, 'entrezgene': '64240', 'type_of_gene': 'protein-coding'}, {'query': 'ABCG8', '_id': '64241', '_score': 17.497955, 'entrezgene': '64241', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD1', '_id': '84696', '_score': 18.64214, 'entrezgene': '84696', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD10', '_id': '55347', '_score': 18.176058, 'entrezgene': '55347', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD11', '_id': '83451', '_score': 17.446537, 'entrezgene': '83451', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD12', '_id': '26090', '_score': 17.526083, 'entrezgene': '26090', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD12B', '_id': '145447', '_score': 18.280773, 'entrezgene': '145447', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD13', '_id': '84945', '_score': 17.485802, 'entrezgene': '84945', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD14A', '_id': '25864', '_score': 17.731777, 'entrezgene': '25864', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD14A-ACY1', '_id': '100526760', '_score': 27.5244, 'entrezgene': '100526760', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD14B', '_id': '84836', '_score': 17.80038, 'entrezgene': '84836', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD15', '_id': '116236', '_score': 18.310272, 'entrezgene': '116236', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD16A', '_id': '7920', '_score': 17.79165, 'entrezgene': '7920', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD16B', '_id': '140701', '_score': 19.079681, 'entrezgene': '140701', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD17A', '_id': '81926', '_score': 18.216496, 'entrezgene': '81926', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD17B', '_id': '51104', '_score': 17.51909, 'entrezgene': '51104', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD17C', '_id': '58489', '_score': 17.55554, 'entrezgene': '58489', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD18', '_id': '80167', '_score': 17.474707, 'entrezgene': '80167', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD2', '_id': '11057', '_score': 18.068645, 'entrezgene': '11057', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD3', '_id': '171586', '_score': 17.494146, 'entrezgene': '171586', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD4', '_id': '63874', '_score': 17.914276, 'entrezgene': '63874', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD5', '_id': '51099', '_score': 18.05728, 'entrezgene': '51099', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD6', '_id': '57406', '_score': 18.179453, 'entrezgene': '57406', 'type_of_gene': 'protein-coding'}, {'query': 'ABHD8', '_id': '79575', '_score': 18.138725, 'entrezgene': '79575', 'type_of_gene': 'protein-coding'}, {'query': 'ABI1', '_id': '10006', '_score': 18.094324, 'entrezgene': '10006', 'type_of_gene': 'protein-coding'}, {'query': 'ABI2', '_id': '10152', '_score': 18.079525, 'entrezgene': '10152', 'type_of_gene': 'protein-coding'}, {'query': 'ABI3', '_id': '51225', '_score': 18.208872, 'entrezgene': '51225', 'type_of_gene': 'protein-coding'}, {'query': 'ABI3BP', '_id': '25890', '_score': 18.232252, 'entrezgene': '25890', 'type_of_gene': 'protein-coding'}, {'query': 'ABITRAM', '_id': '54942', '_score': 17.378248, 'entrezgene': '54942', 'type_of_gene': 'protein-coding'}, {'query': 'ABL1', '_id': '25', '_score': 17.468401, 'entrezgene': '25', 'type_of_gene': 'protein-coding'}, {'query': 'ABL2', '_id': '27', '_score': 17.452177, 'entrezgene': '27', 'type_of_gene': 'protein-coding'}, {'query': 'ABLIM1', '_id': '3983', '_score': 18.035698, 'entrezgene': '3983', 'type_of_gene': 'protein-coding'}, {'query': 'ABLIM2', '_id': '84448', '_score': 17.459743, 'entrezgene': '84448', 'type_of_gene': 'protein-coding'}, {'query': 'ABLIM3', '_id': '22885', '_score': 17.416977, 'entrezgene': '22885', 'type_of_gene': 'protein-coding'}, {'query': 'ABO', '_id': '28', '_score': 18.149904, 'entrezgene': '28', 'type_of_gene': 'protein-coding'}, {'query': 'ABR', '_id': '29', '_score': 17.500183, 'entrezgene': '29', 'type_of_gene': 'protein-coding'}, {'query': 'ABRA', '_id': '137735', '_score': 18.161674, 'entrezgene': '137735', 'type_of_gene': 'protein-coding'}, {'query': 'ABRACL', '_id': '58527', '_score': 17.518393, 'entrezgene': '58527', 'type_of_gene': 'protein-coding'}, {'query': 'ABRAXAS1', '_id': '84142', '_score': 17.502537, 'entrezgene': '84142', 'type_of_gene': 'protein-coding'}, {'query': 'ABRAXAS2', '_id': '23172', '_score': 17.432255, 'entrezgene': '23172', 'type_of_gene': 'protein-coding'}, {'query': 'ABT1', '_id': '29777', '_score': 17.751282, 'entrezgene': '29777', 'type_of_gene': 'protein-coding'}, {'query': 'ABTB1', '_id': '80325', '_score': 17.444893, 'entrezgene': '80325', 'type_of_gene': 'protein-coding'}, {'query': 'ABTB2', '_id': '25841', '_score': 18.152346, 'entrezgene': '25841', 'type_of_gene': 'protein-coding'}, {'query': 'AC000093.1', 'notfound': True}, {'query': 'AC000120.2', 'notfound': True}, {'query': 'AC000120.3', 'notfound': True}, {'query': 'AC001226.2', 'notfound': True}, {'query': 'AC002094.3', 'notfound': True}, {'query': 'AC002310.4', 'notfound': True}, {'query': 'AC002985.1', 'notfound': True}, {'query': 'AC002996.1', 'notfound': True}, {'query': 'AC003002.1', 'notfound': True}, {'query': 'AC003002.2', 'notfound': True}, {'query': 'AC003002.3', 'notfound': True}, {'query': 'AC003005.1', 'notfound': True}, {'query': 'AC003006.1', 'notfound': True}, {'query': 'AC003688.1', 'notfound': True}, {'query': 'AC004076.1', 'notfound': True}, {'query': 'AC004080.3', 'notfound': True}, {'query': 'AC004223.3', 'notfound': True}, {'query': 'AC004593.3', 'notfound': True}, {'query': 'AC004687.2', 'notfound': True}, {'query': 'AC004691.2', 'notfound': True}, {'query': 'AC004706.3', 'notfound': True}, {'query': 'AC004805.1', 'notfound': True}, {'query': 'AC004832.3', 'notfound': True}, {'query': 'AC004922.1', 'notfound': True}, {'query': 'AC004997.1', 'notfound': True}, {'query': 'AC005020.2', 'notfound': True}, {'query': 'AC005041.1', 'notfound': True}, {'query': 'AC005154.5', 'notfound': True}, {'query': 'AC005258.1', 'notfound': True}, {'query': 'AC005324.3', 'notfound': True}, {'query': 'AC005324.4', 'notfound': True}, {'query': 'AC005520.1', 'notfound': True}, {'query': 'AC005551.1', 'notfound': True}, {'query': 'AC005670.2', 'notfound': True}, {'query': 'AC005697.1', 'notfound': True}, {'query': 'AC005702.1', 'notfound': True}, {'query': 'AC005726.1', 'notfound': True}, {'query': 'AC005832.4', 'notfound': True}, {'query': 'AC005833.1', 'notfound': True}, {'query': 'AC005837.2', 'notfound': True}, {'query': 'AC005943.1', 'notfound': True}, {'query': 'AC006030.1', 'notfound': True}, {'query': 'AC006059.2', 'notfound': True}, {'query': 'AC006064.6', 'notfound': True}, {'query': 'AC006254.1', 'notfound': True}, {'query': 'AC006486.1', 'notfound': True}, {'query': 'AC006538.2', 'notfound': True}, {'query': 'AC006978.2', 'notfound': True}, {'query': 'AC007040.2', 'notfound': True}, {'query': 'AC007192.1', 'notfound': True}, {'query': 'AC007244.1', 'notfound': True}, {'query': 'AC007326.4', 'notfound': True}, {'query': 'AC007375.2', 'notfound': True}, {'query': 'AC007731.4', 'notfound': True}, {'query': 'AC007846.2', 'notfound': True}, {'query': 'AC007906.2', 'notfound': True}, {'query': 'AC007998.2', 'notfound': True}, {'query': 'AC008012.1', 'notfound': True}, {'query': 'AC008073.3', 'notfound': True}, {'query': 'AC008162.2', 'notfound': True}, {'query': 'AC008397.1', 'notfound': True}, {'query': 'AC008397.2', 'notfound': True}, {'query': 'AC008403.1', 'notfound': True}, {'query': 'AC008481.3', 'notfound': True}, {'query': 'AC008537.1', 'notfound': True}, {'query': 'AC008575.1', 'notfound': True}, {'query': 'AC008581.2', 'notfound': True}, {'query': 'AC008676.3', 'notfound': True}, {'query': 'AC008687.1', 'notfound': True}, {'query': 'AC008687.4', 'notfound': True}, {'query': 'AC008687.8', 'notfound': True}, {'query': 'AC008695.1', 'notfound': True}, {'query': 'AC008750.8', 'notfound': True}, {'query': 'AC008758.1', 'notfound': True}, {'query': 'AC008758.5', 'notfound': True}, {'query': 'AC008758.6', 'notfound': True}, {'query': 'AC008763.2', 'notfound': True}, {'query': 'AC008763.3', 'notfound': True}, {'query': 'AC008764.1', 'notfound': True}, {'query': 'AC008764.4', 'notfound': True}, {'query': 'AC008770.1', 'notfound': True}, {'query': 'AC008770.2', 'notfound': True}, {'query': 'AC008770.4', 'notfound': True}, {'query': 'AC008878.1', 'notfound': True}, {'query': 'AC008878.2', 'notfound': True}, {'query': 'AC008878.3', 'notfound': True}, {'query': 'AC008982.1', 'notfound': True}, {'query': 'AC009070.1', 'notfound': True}, {'query': 'AC009133.6', 'notfound': True}, {'query': 'AC009163.3', 'notfound': True}, {'query': 'AC009163.5', 'notfound': True}, {'query': 'AC009412.1', 'notfound': True}, {'query': 'AC009690.1', 'notfound': True}, {'query': 'AC009690.3', 'notfound': True}, {'query': 'AC009779.3', 'notfound': True}, {'query': 'AC009879.2', 'notfound': True}, {'query': 'AC009879.3', 'notfound': True}, {'query': 'AC010132.3', 'notfound': True}, {'query': 'AC010197.2', 'notfound': True}, {'query': 'AC010255.3', 'notfound': True}, {'query': 'AC010319.2', 'notfound': True}, {'query': 'AC010323.1', 'notfound': True}, {'query': 'AC010325.1', 'notfound': True}, {'query': 'AC010326.2', 'notfound': True}, {'query': 'AC010327.2', 'notfound': True}, {'query': 'AC010422.3', 'notfound': True}, {'query': 'AC010422.5', 'notfound': True}, {'query': 'AC010422.6', 'notfound': True}, {'query': 'AC010422.8', 'notfound': True}, {'query': 'AC010463.1', 'notfound': True}, {'query': 'AC010522.1', 'notfound': True}, {'query': 'AC010531.1', 'notfound': True}, {'query': 'AC010542.3', 'notfound': True}, {'query': 'AC010547.4', 'notfound': True}, {'query': 'AC010615.4', 'notfound': True}, {'query': 'AC010616.1', 'notfound': True}, {'query': 'AC010619.1', 'notfound': True}, {'query': 'AC010646.1', 'notfound': True}, {'query': 'AC011005.1', 'notfound': True}, {'query': 'AC011195.2', 'notfound': True}, {'query': 'AC011330.3', 'notfound': True}, {'query': 'AC011448.1', 'notfound': True}, {'query': 'AC011452.1', 'notfound': True}, {'query': 'AC011455.2', 'notfound': True}, {'query': 'AC011462.1', 'notfound': True}, {'query': 'AC011473.4', 'notfound': True}, {'query': 'AC011479.1', 'notfound': True}, {'query': 'AC011498.4', 'notfound': True}, {'query': 'AC011499.1', 'notfound': True}, {'query': 'AC011511.1', 'notfound': True}, {'query': 'AC011511.4', 'notfound': True}, {'query': 'AC011530.1', 'notfound': True}, {'query': 'AC011604.2', 'notfound': True}, {'query': 'AC012184.2', 'notfound': True}, {'query': 'AC012213.5', 'notfound': True}, {'query': 'AC012254.2', 'notfound': True}, {'query': 'AC012309.1', 'notfound': True}, {'query': 'AC012488.2', 'notfound': True}, {'query': 'AC012531.3', 'notfound': True}, {'query': 'AC012651.1', 'notfound': True}, {'query': 'AC013271.1', 'notfound': True}, {'query': 'AC013394.1', 'notfound': True}, {'query': 'AC013470.2', 'notfound': True}, {'query': 'AC013489.1', 'notfound': True}, {'query': 'AC013717.1', 'notfound': True}, {'query': 'AC015688.4', 'notfound': True}, {'query': 'AC015802.6', 'notfound': True}, {'query': 'AC015813.2', 'notfound': True}, {'query': 'AC015871.1', 'notfound': True}, {'query': 'AC017083.3', 'notfound': True}, {'query': 'AC018362.3', 'notfound': True}, {'query': 'AC018512.1', 'notfound': True}, {'query': 'AC018523.2', 'notfound': True}, {'query': 'AC018630.2', 'notfound': True}, {'query': 'AC018709.1', 'notfound': True}, {'query': 'AC018755.2', 'notfound': True}, {'query': 'AC019117.3', 'notfound': True}, {'query': 'AC019257.8', 'notfound': True}, {'query': 'AC020636.2', 'notfound': True}, {'query': 'AC020907.6', 'notfound': True

In [17]:
ad.var

        EntrezGene RNA_Biotype
GENE
A1BG           NaN         NaN
A1CF           NaN         NaN
A2M            NaN         NaN
A2ML1          NaN         NaN
A3GALT2        NaN         NaN
...            ...         ...
ZXDC           NaN         NaN
ZYG11A         NaN         NaN
ZYG11B         NaN         NaN
ZYX            NaN         NaN
ZZEF1          NaN         NaN

[19933 rows x 2 columns]

In [33]:
ad

AnnData object with n_obs × n_vars = 111 × 19933
    obs: 'ABT-199', 'ExVivo_SampleID', 'patientID'
    layers: None (.X)

In [34]:
import mygene
mg = mygene.MyGeneInfo()

In [83]:
expr_df = ad.to_df()
non_ig = []
for col in expr_df.columns:
    if not col.startswith("IGH") or not col.startswith("IGK") or not col.startswith("IGL"):
        non_ig.append(col)
expr_df[non_ig]

GENE,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1
RNA_SampleID,,,,,,,,,,,,,,,,,,,,,
SL414065,1.029276,-4.035047,-0.087733,-9.965784,-9.965784,-3.816037,-9.965784,6.022168,3.117861,-5.011588,...,3.058490,1.351063,2.293076,2.114700,2.347949,2.914756,-3.457990,2.278282,3.506018,4.605317
SL316611,3.276646,-9.965784,4.000992,-4.035047,-9.965784,-3.171368,-9.965784,4.777209,1.401084,-9.965784,...,1.795351,0.911500,0.757877,1.433494,1.057277,2.007554,-2.465938,1.803640,4.921294,3.889571
SL399348,2.111365,-3.307573,1.496207,-9.965784,-9.965784,-3.816037,-9.965784,3.617181,0.848798,-9.965784,...,1.138159,0.566572,-0.356606,2.114700,2.226817,1.761711,-2.932361,0.633199,1.941482,1.868292
SL242336,-0.808437,-9.965784,1.956428,-9.965784,-9.965784,-4.035047,-5.573467,4.056670,0.934328,-9.965784,...,2.916668,2.928086,3.421021,2.104672,0.816395,2.451805,-9.965784,2.167037,0.678973,2.864137
SL414057,1.765959,-4.035047,1.815985,-9.965784,-9.965784,-2.547932,-9.965784,4.927470,1.183328,-5.573467,...,2.339422,0.740712,0.740712,1.876173,1.351063,1.856388,-1.117161,1.609282,2.422502,3.184439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SL432596,0.903810,-3.625934,1.124990,-9.965784,-9.965784,-1.732165,-9.965784,4.996886,1.521553,-9.965784,...,2.316435,2.784713,2.858180,1.807767,1.091531,2.239092,-0.471929,1.891808,3.034040,3.373091
SL425882,-0.471929,-9.965784,2.929980,-9.965784,-9.965784,-0.492079,-4.293359,5.073863,1.433494,-6.506353,...,2.493391,3.053285,2.127963,0.799916,0.537048,2.195663,-2.052895,1.345396,3.577852,3.137667
SL240795,-1.181149,-9.965784,2.220640,-9.965784,-9.965784,-4.035047,-9.965784,4.035712,1.996750,-9.965784,...,1.678523,2.011138,-0.320126,2.269332,1.417380,1.618709,-1.732165,1.880098,1.926379,3.209609
SL240938,1.832282,-9.965784,-3.307573,-9.965784,-9.965784,-9.965784,-9.965784,4.458185,1.118360,-9.965784,...,1.050328,1.556307,0.029983,2.018278,1.328262,0.971590,-9.965784,1.422771,1.151209,2.707304
SL242345,2.742222,-9.965784,1.891808,-3.457990,-9.965784,-6.506353,-9.965784,3.713806,0.412511,-9.965784,...,1.050328,0.926759,-0.320126,0.390668,0.125651,0.486457,-4.608232,1.183328,3.531194,2.680549

In [84]:
#out = mg.querymany(list(ad.to_df().columns), scopes="alias,symbol", fields="ensembl.gene, type_of_gene, hgnc, entrezgene", species="human")
out = mg.querymany(list(expr_df.columns), scopes="alias,symbol", fields="type_of_gene,entrezgene", species="human")

742 input query terms found dup hits:	[('ACAT1', 2), ('ACAT2', 2), ('ACP1', 2), ('ADA2', 2), ('ADAM18', 2), ('ADCY3', 2), ('ADK', 2), ('AD
583 input query terms found no hit:	['AC000093.1', 'AC000120.2', 'AC000120.3', 'AC001226.2', 'AC002094.3', 'AC002310.4', 'AC002985.1', '

In [85]:
import pandas as pd
df = pd.DataFrame(out)

In [86]:

df = df[df["type_of_gene"] == 'protein-coding']

In [87]:
print(df['entrezgene'])

0             1
1         29974
2             2
3        144568
4        127550
          ...
20775     79364
20776    440590
20777     79699
20778      7791
20779     23140
Name: entrezgene, Length: 19936, dtype: str

In [88]:
df[df["query"] == "BCL2"]

     query  _id    _score entrezgene    type_of_gene notfound
2088  BCL2  596  18.14115        596  protein-coding      NaN

In [89]:
df

         query     _id     _score entrezgene    type_of_gene notfound
0         A1BG       1  19.544168          1  protein-coding      NaN
1         A1CF   29974  17.505005      29974  protein-coding      NaN
2          A2M       2  19.295105          2  protein-coding      NaN
3        A2ML1  144568  19.148075     144568  protein-coding      NaN
4      A3GALT2  127550  19.185488     127550  protein-coding      NaN
...        ...     ...        ...        ...             ...      ...
20775     ZXDC   79364  18.242882      79364  protein-coding      NaN
20776   ZYG11A  440590  19.330933     440590  protein-coding      NaN
20777   ZYG11B   79699  18.906813      79699  protein-coding      NaN
20778      ZYX    7791  17.201742       7791  protein-coding      NaN
20779    ZZEF1   23140  17.432562      23140  protein-coding      NaN

[19936 rows x 6 columns]