In [1]:
from datasets.Harmonized_Datasets import harmonize
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [2]:
mf_ad = harmonize()['Moffitt']
ml_results_df = pd.read_csv("../../outputs/predictions_for_wes_analysis.csv").set_index('samples')
maf = pd.read_csv("../../data/Moffitt/Whole_Exome/MAF.maf", sep='\t').set_index('sampleID')

/usr/lib/python3.14/functools.py:982: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)
/usr/lib/python3.14/functools.py:982: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

Moffitt Annotated data found!
CoMMpass Annotated data found!

/usr/lib/python3.14/functools.py:982: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

DeCampos Annotated data found!
Number of Harmonized Genes: 18676

FileNotFoundError: [Errno 2] No such file or directory: '../../outputs/predictions_for_wes_analysis.csv'

In [ ]:
maf=maf[maf['Hugo_Symbol'] !='Unknown']

In [ ]:
non_synonymous_mutations = ['Frame_Shift_Ins', 'Frame_Shift_Del', 'Nonsense_Mutation', 'In_Frame_Ins', 'Nonstop_Mutation', 'In_Frame_Del', 'Missense_Mutation']

In [ ]:
maf

,chr,pos,ref,alt,REF,ALT,Variant_Type,Variant_Classification,Start,End,Hugo_Symbol,Tumor_Sample_Barcode,Chromosome,Start_Position,End_Position,Reference_Allele,Tumor_Seq_Allele2,AAChange
sampleID,,,,,,,,,,,,,,,,,,
SL429256,chr1,15580126,G,A,G,A,SNP,Silent,15580126,15580127,AGMAT,SL429256,chr1,15580126,15580127,G,A,p.I164I
SL429256,chr1,19095047,T,C,T,C,SNP,Intron,19095047,19095048,UBR4,SL429256,chr1,19095047,19095048,T,C,[UBR4
SL429256,chr1,20981250,A,T,A,T,SNP,Intron,20981250,20981251,EIF4G3,SL429256,chr1,20981250,20981251,A,T,[EIF4G3
SL429256,chr1,22511093,CTTT,C,CTTT,C,DEL,Intron,22511093,22511097,ZBTB40,SL429256,chr1,22511093,22511097,CTTT,C,[ZBTB40
SL429256,chr1,26344170,C,T,C,T,SNP,Missense_Mutation,26344170,26344171,CRYBG2,SL429256,chr1,26344170,26344171,C,T,p.E1154K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SL216928,chrX,116173162,A,T,A,T,SNP,Silent,116173162,116173163,AGTR2,SL216928,chrX,116173162,116173163,A,T,p.A294A
SL216928,chrX,123960861,G,T,G,T,SNP,5'UTR,123960861,123960862,STAG2,SL216928,chrX,123960861,123960862,G,T,[STAG2
SL216928,chrX,135574082,CTTT,C,CTTT,C,DEL,Intron,135574082,135574086,INTS6L,SL216928,chrX,135574082,135574086,CTTT,C,[INTS6L
SL216928,chrX,153941487,G,T,G,T,SNP,Nonsense_Mutation,153941487,153941488,RENBP,SL216928,chrX,153941487,153941488,G,T,p.C312*
SL216928,chrY,13298965,G,T,G,T,SNP,Missense_Mutation,13298965,13298966,UTY,SL216928,chrY,13298965,13298966,G,T,p.P1190Q

In [ ]:
maf = maf[maf['Variant_Classification'].isin(non_synonymous_mutations)]

In [ ]:
#ras_genes = ['HRAS', "KRAS", "NRAS", "BRAF"]
ras_genes = ["KRAS"]
maf = maf[maf['Hugo_Symbol'].isin(ras_genes)]

In [ ]:
maf

,chr,pos,ref,alt,REF,ALT,Variant_Type,Variant_Classification,Start,End,Hugo_Symbol,Tumor_Sample_Barcode,Chromosome,Start_Position,End_Position,Reference_Allele,Tumor_Seq_Allele2,AAChange
sampleID,,,,,,,,,,,,,,,,,,
SL395003,chr12,25245347,C,T,C,T,SNP,Missense_Mutation,25245347,25245348,KRAS,SL395003,chr12,25245347,25245348,C,T,p.G13D
SL395003,chr12,25245350,C,A,C,A,SNP,Missense_Mutation,25245350,25245351,KRAS,SL395003,chr12,25245350,25245351,C,A,p.G12V
SL217784,chr12,25227341,T,G,T,G,SNP,Missense_Mutation,25227341,25227342,KRAS,SL217784,chr12,25227341,25227342,T,G,p.Q61H
SL265349,chr12,25245348,C,A,C,A,SNP,Missense_Mutation,25245348,25245349,KRAS,SL265349,chr12,25245348,25245349,C,A,p.G13C
SL237983,chr12,25227341,T,G,T,G,SNP,Missense_Mutation,25227341,25227342,KRAS,SL237983,chr12,25227341,25227342,T,G,p.Q61H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SL250830,chr12,25245347,C,T,C,T,SNP,Missense_Mutation,25245347,25245348,KRAS,SL250830,chr12,25245347,25245348,C,T,p.G13D
SL238076,chr12,25245347,C,T,C,T,SNP,Missense_Mutation,25245347,25245348,KRAS,SL238076,chr12,25245347,25245348,C,T,p.G13D
SL393235,chr12,25245351,C,G,C,G,SNP,Missense_Mutation,25245351,25245352,KRAS,SL393235,chr12,25245351,25245352,C,G,p.G12R
SL399823,chr12,25227341,T,G,T,G,SNP,Missense_Mutation,25227341,25227342,KRAS,SL399823,chr12,25227341,25227342,T,G,p.Q61H
SL399823,chr12,25227342,T,A,T,A,SNP,Missense_Mutation,25227342,25227343,KRAS,SL399823,chr12,25227342,25227343,T,A,p.Q61L

In [ ]:
mf_ad.obs

,ABT-199,ExVivo_SampleID,patientID,t11_14,WES_SampleID,Disease_Status
RNA_SampleID,,,,,,
SL414065,68.289579,Pt429,GDH03df143c,NaN,SL409637,ERMM
SL316611,96.238950,Pt227,GDH08065638,0.0,NaN,LRMM
SL399348,65.236880,Pt382,GDH087884bf,0.0,SL393230,ERMM
SL242336,81.704820,Pt166,GDH0bd4be69,1.0,SL241599,LRMM
SL414057,86.576130,Pt419,GDH10e17fff,NaN,SL409628,ERMM
...,...,...,...,...,...,...
SL432596,100.000000,Pt516,GDHea79fae2,NaN,SL434811,ERMM
SL425882,99.259752,Pt478,GDHefa46356,NaN,SL426500,LRMM
SL240795,88.815766,Pt143,GDHf5b6b0bc,0.0,SL241566,ERMM
SL240938,79.784322,Pt142,GDHf7b6f129,1.0,SL239827,NDMM
SL242345,91.446859,Pt149,GDHf934857e,0.0,SL241577,ERMM

In [ ]:
tmb = {}
for wes_id, rna_id in zip(mf_ad.obs['WES_SampleID'], mf_ad.obs.index):
    if not pd.isna(wes_id):
        if wes_id in maf.index:
            tmb[rna_id] = [len(maf.loc[wes_id]), wes_id]
        
tmb = pd.DataFrame(tmb, index=['TMB', 'WES_SampleID']).T

In [ ]:
tmb

         TMB WES_SampleID
SL414065  18     SL409637
SL242336  18     SL241599
SL414057  18     SL409628
SL432595   2     SL434810
SL425902  18     SL426497
SL375774  18     SL374463
SL375775  18     SL374464
SL375776  18     SL374465
SL399200  18     SL393226
SL250130  18     SL249672
SL399316  18     SL393209
SL405557  18     SL394996
SL404331  18     SL380856
SL375779  18     SL374473
SL240856  18     SL241567
SL399354  18     SL393241
SL432586  18     SL434801
SL310718  18     SL281122
SL405630  18     SL394998
SL375745  18     SL374462
SL390296  18     SL380824
SL405727   2     SL399819
SL375766  18     SL374449
SL375771  18     SL374457
SL375777  18     SL374466
SL375749   2     SL374471
SL399321  18     SL393224
SL426773  18     SL429257
SL425877  18     SL426496
SL432584  18     SL434799
SL432596  18     SL434811
SL240795   3     SL241566

In [ ]:
mf_ad = mf_ad[mf_ad.obs.index.isin(tmb.index)] # this will also align the indices

In [ ]:
mf_ad.obs['TMB'] = tmb['TMB']

/tmp/ipykernel_42216/1492951643.py:1: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  mf_ad.obs['TMB'] = tmb['TMB']

In [ ]:
mf_ad.obs[['y_true', 'y_pred', 'y_prob']] = ml_results_df[['y_true', 'y_pred', 'y_prob']]

In [ ]:
# remove 'moderate response' samples but I can try using the model ot predict their response
mf_ad = mf_ad[mf_ad.obs['y_pred'].notna()]

In [ ]:
mf_ad.obs

,ABT-199,ExVivo_SampleID,patientID,t11_14,WES_SampleID,Disease_Status,TMB,y_true,y_pred,y_prob
RNA_SampleID,,,,,,,,,,
SL414065,68.289579,Pt429,GDH03df143c,NaN,SL409637,ERMM,18,1.0,1.0,0.998809
SL425902,69.064942,Pt466,GDH2cfbecf9,NaN,SL426497,ERMM,18,1.0,1.0,0.532778
SL375774,92.732071,Pt254,GDH33616fbc,0.0,SL374463,LRMM,18,0.0,0.0,0.000014
SL375775,100.000000,Pt276,GDH33616fbc,0.0,SL374464,LRMM,18,0.0,0.0,0.001411
SL375776,100.000000,Pt303,GDH33616fbc,0.0,SL374465,LRMM,18,0.0,0.0,0.001764
SL399200,92.439678,Pt375,GDH346f3bca,0.0,SL393226,LRMM,18,0.0,1.0,0.544088
SL250130,35.313761,Pt169,GDH3e41bb01,1.0,SL249672,ERMM,18,1.0,0.0,0.254232
SL399316,79.657295,Pt380,GDH3f8637fc,0.0,SL393209,ERMM,18,1.0,1.0,0.999773
SL404331,58.266370,Pt348,GDH501e7d68,1.0,SL380856,NDMM,18,1.0,1.0,0.710794
SL375779,97.133922,Pt193,GDH525bde95,0.0,SL374473,LRMM,18,0.0,0.0,0.000954
SL310718,94.277922,Pt220,GDH6e57bc32,1.0,SL281122,LRMM,18,0.0,1.0,0.850203
SL405630,66.484325,Pt397,GDH974f5b9f,1.0,SL394998,ERMM,18,1.0,1.0,0.997287
SL375745,93.127658,Pt290,GDH99e3ea52,0.0,SL374462,NDMM,18,0.0,1.0,0.953508
SL405727,68.139779,Pt403,GDH9db255c9,NaN,SL399819,ERMM,2,1.0,1.0,0.676738
SL375766,73.765624,Pt293,GDHa7fe3948,0.0,SL374449,ERMM,18,1.0,0.0,0.016452
SL375771,59.454005,Pt304,GDHa8348085,0.0,SL374457,LRMM,18,1.0,0.0,0.066710
SL375777,71.104209,Pt196,GDHb09cf73a,0.0,SL374466,ERMM,18,1.0,1.0,0.603146
SL375749,31.359684,Pt235,GDHbb39a20a,0.0,SL374471,NDMM,2,1.0,0.0,0.332215
SL399321,70.901785,Pt373,GDHbcb16b37,1.0,SL393224,ERMM,18,1.0,1.0,0.999740
SL432584,65.712897,Pt495,GDHe3530ae7,NaN,SL434799,NDMM,18,1.0,1.0,0.876005
SL432596,100.000000,Pt516,GDHea79fae2,NaN,SL434811,ERMM,18,0.0,0.0,0.326034

In [ ]:
mf_ad.obs['t11_14'] = pd.Categorical(mf_ad.obs['t11_14'])

/tmp/ipykernel_42216/2517161883.py:1: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  mf_ad.obs['t11_14'] = pd.Categorical(mf_ad.obs['t11_14'])

In [ ]:
# Regression Analysis
mf_ad_og = mf_ad.copy()
mf_ad = mf_ad[mf_ad.obs['t11_14'].notna()]

# single coefficients
y = mf_ad.obs['ABT-199']



model_1 = sm.OLS(y, sm.add_constant(mf_ad.obs['t11_14'])).fit(cov_type='HC3')
model_2 = sm.OLS(y, sm.add_constant(mf_ad.obs['y_prob'])).fit(cov_type='HC3')
model_3 = sm.OLS(y ,sm.add_constant(mf_ad.obs['TMB'])).fit(cov_type='HC3')

# two coefficients
x_4 = sm.add_constant(np.column_stack(
   [ mf_ad.obs['t11_14'], mf_ad.obs['y_prob'] ]
        )  
    )
model_4 = sm.OLS(y,x_4).fit(cov_type='HC3')

x_5 = sm.add_constant(np.column_stack(
   [ mf_ad.obs['t11_14'], mf_ad.obs['TMB'] ]
        )  
    )
model_5 = sm.OLS(y,x_5).fit(cov_type='HC3')

x_6 = sm.add_constant(np.column_stack([mf_ad.obs['y_prob'], mf_ad.obs['TMB']]))
model_6 = sm.OLS(y, x_6).fit(cov_type='HC3')

# three coefficients 
x_7 = sm.add_constant(np.column_stack(
   [ mf_ad.obs['t11_14'], mf_ad.obs['TMB'], mf_ad.obs['y_prob'] ]
        )  
    )
model_7 = sm.OLS(y,x_7).fit(cov_type='HC3')

print(f't11;14 status only: { model_1.rsquared}')

print(f'model probs only: {model_2.rsquared}')


print(f'tumor burden only: {model_3.rsquared}')

print(f'model probs and t11;14 status: {model_4.rsquared}')

print(f't11;14 status + tumor burden: {model_5.rsquared}')

print(f'model probability + tumor burden: {model_6.rsquared}')

print(f'model probability + tumor burden + t11;14 status: {model_7.rsquared}')

t11;14 status only: 0.12164522392406663
model probs only: 0.0075628380350367674
tumor burden only: 0.29640919774385566
model probs and t11;14 status: 0.1325888223033972
t11;14 status + tumor burden: 0.49929444016533786
model probability + tumor burden: 0.31363893360517225
model probability + tumor burden + t11;14 status: 0.5114541415564284

In [ ]:
model_4.wald_test('x2 = 0', use_f=True)

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=0.20022480940078619, p=0.6619045688230332, df_denom=13, df_num=1>

In [ ]:

# does y_prob + TMB add beyond t11;14?
print(model_7.wald_test('x2 = 0, x3 = 0', use_f=True))

# does  TMB add beyond t11;14?
print(model_7.wald_test('x2 = 0', use_f=True))

# does y_prob add beyond t11;14 + TMB? 
print(model_7.wald_test('x3 = 0', use_f=True))

<F test: F=2.3361938989351163, p=0.1390274816546331, df_denom=12, df_num=2>
<F test: F=4.379691217222319, p=0.05828805187456776, df_denom=12, df_num=1>
<F test: F=0.22408641363956108, p=0.6444389704284883, df_denom=12, df_num=1>

In [ ]:
mutation_matrix = {}

for gene in maf['Hugo_Symbol']:
    gene_maf = maf[maf['Hugo_Symbol'] == gene]
    for variant in gene_maf['Variant_Classification']:
        col_name = str(gene)+str(variant)
        gene_variant_maf = gene_maf[gene_maf['Variant_Classification'] == variant]
        mutation_matrix[col_name] = []
        for wes_id, rna_id in zip(mf_ad.obs['WES_SampleID'], mf_ad.obs.index):
            if not pd.isna(wes_id):
                if wes_id in gene_variant_maf.index:
                    count = [len(gene_variant_maf.loc[wes_id])]
                    mutation_matrix[col_name].append(count)

In [ ]:
mutation_matrix